project_id = "kigmecfevnbzmobvmumm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = false
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
max_frequency = "1s"

[auth.sms]
enable_signup = false
enable_confirmations = false
max_frequency = "5s"

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = 8083

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[experimental]
orioledb_version = ""
s3_host = "env(S3_HOST)"
s3_region = "env(S3_REGION)"
s3_access_key_id = "env(S3_ACCESS_KEY_ID)"
s3_secret_access_key = "env(S3_SECRET_ACCESS_KEY)"

[functions.manage-users]
verify_jwt = true

[functions.parse-diet-pdf]
verify_jwt = true

[functions.parse-guidelines-pdf]
verify_jwt = true

[functions.generate-shopping-list]
verify_jwt = true

[functions.parse-body-measurements-pdf]
verify_jwt = true

[functions.get-billing-info]
verify_jwt = true

[functions.get-billing-otp]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true

[functions.check-subscription-status]
verify_jwt = true

[functions.restart-subscription]
verify_jwt = true

[functions.update-subscription-status]
verify_jwt = false

[functions.register-nutritionist]
verify_jwt = false
