// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kigmecfevnbzmobvmumm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpZ21lY2Zldm5iem1vYnZtdW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MTIzNzQsImV4cCI6MjA3NjE4ODM3NH0.yPof__EYwuO3kAntdHoW6JWA2uxrLtrkiAsnxg1fSgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});